version: '2'

tasks:

## Task Groups
  structure:
    cmds:
      - mkdir -p ca/root ca/intermediate
      - mkdir -p config/
      - mkdir -p certs/consul/servers
      - mkdir -p certs/consul/clients
      - mkdir -p certs/nomad/servers
      - mkdir -p certs/nomad/clients
      - mkdir -p certs/vault/servers
      - mkdir -p certs/vault/clients
  
  gen-all-ca:
    cmds:
      - task: structure
      - task: ca-csr
      - task: intermediate-ca-csr
      - task: ca-config
      - task: intermediate-ca-config
      - task: ca
      - task: intermediate-ca

  gen-all-consul:
    cmds:
      - task: alpha-consul-servers-csr
      - task: consul-servers
      - task: consul-client-csrs
      - task: consul-clients-certs

  gen-all-nomad:
    cmds:
      - rm -rf certs/nomad
      - mkdir -p certs/nomad/servers
      - mkdir -p certs/nomad/clients
      
      - task: nomad-servers-csr
      - task: nomad-clients-csr
      - task: nomad-client-certs
      - task: nomad-servers-certs

  gen-all-vault:
    cmds:
      - task: vault-servers-certs
      - task: vault-cli-client-csr
      - task: vault-app-client-csr
      - task: vault-cli-cert
      - task: vault-app-client-cert

  gen-nomad-cli-client:
    cmds:
      - task: nomad-cli-clients-csr
      - task: nomad-cli-client-certs
  reset:
    cmds:
      - rm -rf ca config certs
      # - task: main

  consul-client-csrs:
    silent: true
    cmds:
      - task: consul-vault-client-csr
      - task: consul-nomad-client-csr
      - task: consul-cli-client-csr
      - task: consul-client-csr

  consul-clients-certs:
    silent: true
    cmds:
      - task: consul-vault-cert
      - task: consul-nomad-cert
      - task: consul-cli-cert
      - task: consul-client-cert

# Individual Tasks
  ca:
    desc: Generate root CA
    cmds:
      - cfssl genkey -initca ca/root/ca-csr.json | cfssljson -bare ca/root/ca
  
  intermediate-ca:
    desc: Generate intermediate CA
    # dir: ca/intermediate
    cmds:
      - |
        cfssl gencert -ca=ca/root/ca.pem \
        -ca-key=ca/root/ca-key.pem \
        -config=config/intermediate-ca-config.json \
        ca/intermediate/intermediate-ca-csr.json | \
        cfssljson -bare ca/intermediate/intermediate-ca
  
  ca-csr:
    desc: Generate the CA CSR
    silent: true
    cmds:
      - echo {{.ROOT_CA_CSR_JSON | catLines}} > ca/root/ca-csr.json

  intermediate-ca-csr:
    desc: Generate the CA CSR
    silent: true
    cmds:
      - echo {{.INTERMEDIATE_CA_CSR_JSON | catLines}} > ca/intermediate/intermediate-ca-csr.json

  intermediate-ca-config:
    desc: Generate Intermediate CA Config file
    silent: true
    cmds:
      -  echo {{.INTERMEDIATE_CA_CONFIG_JSON | catLines}} > config/intermediate-ca-config.json
        
  ca-config:
    desc: Generate CA Config file
    silent: true
    cmds:
      - echo {{.CA_CONFIG_JSON | catLines}} > config/ca-config.json

  alpha-consul-servers-csr:
    silent: true
    cmds:
      - mkdir -p certs/alpha-consul/servers
      - echo {{.ALPHA_CONSUL_SERVERS_CSR | catLines }} > certs/alpha-consul/servers/server-csr.json

  consul-vault-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/consul/clients/vault
      - echo {{.CONSUL_VAULT_CLIENT_CSR_JSON | catLines}} > certs/consul/clients/vault/vault-csr.json

  consul-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/consul/clients/consul
      - echo {{.CONSUL_CLIENT_CSR_JSON | catLines}} > certs/consul/clients/consul/consul-csr.json

  consul-nomad-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/consul/clients/nomad
      - echo {{.CONSUL_NOMAD_CLIENT_CSR_JSON | catLines}} > certs/consul/clients/nomad/nomad-csr.json

  consul-cli-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/consul/clients/cli
      - echo {{.CONSUL_CLI_CLIENT_CSR_JSON | catLines }} > certs/consul/clients/cli/cli-csr.json

  consul-servers:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client-server certs/alpha-consul/servers/server-csr.json | \
        cfssljson -bare certs/consul/servers/vagrant-consul-server
  
  consul-cli-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/consul/clients/cli/cli-csr.json | \
        cfssljson -bare certs/consul/clients/cli/vagrant-consul-cli-client
  
  vault-cli-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/vault/clients/cli
      - echo {{.VAULT_CLI_CLIENT_CSR_JSON | catLines}} > certs/vault/clients/cli/cli-csr.json

  vault-app-client-csr:
    silent: true
    cmds:
      - mkdir -p certs/vault/clients/app
      - echo {{.VAULT_APP_CLIENT_CSR_JSON | catLines}} > certs/vault/clients/app/app-csr.json

  vault-servers-certs:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=server certs/alpha-consul/servers/server-csr.json | \
        cfssljson -bare certs/vault/servers/vagrant-vault-server
  
  vault-cli-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/vault/clients/cli/cli-csr.json | \
        cfssljson -bare certs/vault/clients/cli/vagrant-vault-cli-client

  vault-app-client-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/vault/clients/app/app-csr.json | \
        cfssljson -bare certs/vault/clients/app/vagrant-vault-app-client
  
  consul-nomad-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/consul/clients/nomad/nomad-csr.json | \
        cfssljson -bare certs/consul/clients/nomad/vagrant-consul-nomad-client
  
  consul-vault-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/consul/clients/vault/vault-csr.json | \
        cfssljson -bare certs/consul/clients/vault/vagrant-consul-vault-client
  
  consul-client-cert:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/consul/clients/consul/consul-csr.json | \
        cfssljson -bare certs/consul/clients/consul/vagrant-consul-client
  
# Generate Nomad Certs
# 1. generate nomad servers csr
  nomad-servers-csr:
    silent: true
    cmds:
      - mkdir -p certs/nomad/servers/
      - echo {{.VAGRANT_HASHI_STACK_1_NOMAD_SERVER_CSR_JSON | catLines}} > certs/nomad/servers/vagrant-hashi-stack-1-nomad-csr.json
      - echo {{.VAGRANT_HASHI_STACK_2_NOMAD_SERVER_CSR_JSON | catLines}} > certs/nomad/servers/vagrant-hashi-stack-2-nomad-csr.json
      - echo {{.VAGRANT_HASHI_STACK_3_NOMAD_SERVER_CSR_JSON | catLines}} > certs/nomad/servers/vagrant-hashi-stack-3-nomad-csr.json

# 2. Generate Nomad servers certs
  nomad-servers-certs:
    cmds:
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client-server certs/nomad/servers/vagrant-hashi-stack-1-nomad-csr.json | \
        cfssljson -bare certs/nomad/servers/vagrant-hashi-stack-1-nomad-server
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client-server certs/nomad/servers/vagrant-hashi-stack-2-nomad-csr.json | \
        cfssljson -bare certs/nomad/servers/vagrant-hashi-stack-2-nomad-server
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client-server certs/nomad/servers/vagrant-hashi-stack-3-nomad-csr.json | \
        cfssljson -bare certs/nomad/servers/vagrant-hashi-stack-3-nomad-server
  
# 3. Generate Nomad clients csr
  nomad-clients-csr:
    silent: true
    cmds:
      - mkdir -p certs/nomad/clients/
      - echo {{.NOMAD_CLIENT_CSR_JSON | catLines}} > certs/nomad/clients/nomad-client-csr.json

# 4. Use client csr to generate certs
  nomad-client-certs:
    silent: true
    cmds:
      - mkdir -p certs/nomad/clients/nomad
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client-server certs/nomad/clients/nomad-client-csr.json | \
        cfssljson -bare certs/nomad/clients/nomad/vagrant-nomad-client

# 3. Generate Nomad clients csr
  nomad-cli-clients-csr:
    silent: true
    cmds:
      - mkdir -p certs/nomad/clients/cli
      - echo {{.NOMAD_CLI_CLIENT_CSR_JSON | catLines}} > certs/nomad/clients/cli/nomad-cli-client-csr.json

# 4. Use client csr to generate certs
  nomad-cli-client-certs:
    silent: true
    cmds:
      - mkdir -p certs/nomad/clients/cli
      - |
        cfssl gencert \
        -ca=ca/intermediate/intermediate-ca.pem \
        -ca-key=ca/intermediate/intermediate-ca-key.pem \
        -config=config/ca-config.json \
        -profile=client certs/nomad/clients/cli/nomad-cli-client-csr.json | \
        cfssljson -bare certs/nomad/clients/cli/vagrant-nomad-cli-client
# 5. validate server and client certs
